### ISSUE TITLE
Typo in CountryListFacade

### ISSUE THREAD

**Issue by matzering** [Monarobase/country-list#18]
After updating you very cool package I got an error in my Laravel 5.1 application:

> ReflectionException in Container.php line 741:
> Class countrylist does not exist

Checking your CountryListFacade and found:
`protected static function getFacadeAccessor() { return 'countrylist'; }`
corrected to:
`protected static function getFacadeAccessor() { return 'countryList'; }` 
and it is working like a charm

**Comment by matzering** [comment]
sorry wrong window

**Comment by sebastiaanluca** [comment]
Seems like this package has been abandoned?

Anyhow, the issue above is still happening and makes the package unusable. Not sure why this was closed the same day.
