### ISSUE TITLE
Not Installing in Laravel 7

### ISSUE THREAD

**Issue by rashed50702** [Monarobase/country-list#24]
During installation in Laravel 7, I am getting this error - `    - monarobase/country-list 3.0.0 requires illuminate/support ^5.8|^6.0 -> satisfiable by illuminate/support[5.8.x-dev, 6.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].`

**Comment by WimDeMeester** [comment]
I see the same problem.

**Comment by thujohn** [comment]
Hi.

I just corrected it in 3.1.0

**Comment by WimDeMeester** [comment]
Thanks a lot! Install without problems.

**Comment by suzandi** [comment]
Trying to retrieve the flags.html, after checking a few files, I see that this package does not actually provide the flags of the countries, I am right or completely did not see this function?
