### ISSUE TITLE
Add UK alias for United Kingdom

### ISSUE THREAD

**Issue by Messhias** [Monarobase/country-list#28]
If we insert `UK` to getOne function we get this error:

<img width="1204" alt="Screenshot 2021-06-16 at 11 20 00" src="https://user-images.githubusercontent.com/1161283/122202271-ccb7a080-ce94-11eb-9844-0767a817cc37.png">

But the UK it's a standard for the whole EU and some other countries in the Asia and middle-east (e.g. India, United Arab Emirates, and most countries was a UK colony in the history).

**Comment by Messhias** [comment]
Did someone has checked that?

**Comment by amharris** [comment]
@Messhias The alpha-2 code for the United Kingdom is `GB`, not `UK`.

Wikipedia provides a nice description for the reason, [here](https://en.wikipedia.org/wiki/ISO_3166-1#Coding).
At the time of writing, it states:

> The codes are chosen, according to the ISO 3166/MA, "to reflect the significant, unique component of the country name in order to allow a visual association between country name and country code".[[5]](https://en.wikipedia.org/wiki/ISO_3166-1#cite_note-faqs_specific-5) For this reason, common components of country names like "Republic", "Kingdom", "United", "Federal" or "Democratic" are normally not used for deriving the code elements. As a consequence, for example, the [United Kingdom](https://en.wikipedia.org/wiki/United_Kingdom) is officially assigned the alpha-2 code GB rather than UK, based on its official name "United Kingdom of Great Britain and Northern Ireland" (although UK is [reserved](https://en.wikipedia.org/wiki/ISO_3166-1#Reserved_and_user-assigned_code_elements) on the request of the United Kingdom). Some codes are chosen based on the native names of the countries. For example, Germany is assigned the alpha-2 code DE, based on its native name "Deutschland".
