### ISSUE TITLE
Laravel 10 integration

### ISSUE THREAD

**Issue by BrickZ28** [Monarobase/country-list#34]
Will this be updated to work in Laravel 10?

**Comment by thujohn** [comment]
Hi.

You can install the new release.

**Comment by BrickZ28** [comment]
Great, thank you for the quick reply.  I wasn't trying to be pushy or anything just curious if I was going to have to disable it until release.  You have done well!!!!!!!!!

**Comment by tonypartridge** [comment]
This can be closed..
